### ISSUE TITLE
Add offset to rolling_window_sequence primitive 

### ISSUE THREAD

**Issue by skyeeiskowitz** [MLBazaar/MLPrimitives#251]
* MLPrimitives version: v0.2.5
* Python version: 3.6
* Operating System: MacOS Catalina

### Description

Add new `offset` argument to `mlprimitives/primitives/mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences.json`

The offset indicates the number of steps that will be created between the input and the target sequence.

### What I Did
Added argument `offset=0`  to the `rolling_window_sequences` function in `mlprimitives/custom/timeseries_preprocessing.py` 
Added docstring describing offset
Changed `max_start`:
```
max_start = len(X) - window_size - target_size - offset + 1
```

Changed `out_y` and `y_index`:
```
        out_y.append(target[end + offset:end + offset + target_size])
        y_index.append(index[end + offset])
```

Added fixed hyperparameter to the primitive json `mlprimitives/primitives/mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences.json`
```
            "offset": {
                "type": "int",
                "default": 0
            }
```

**Comment by csala** [comment]
Sounds good @skyeeiskowitz ! Please go ahead and do a PR!
