### ISSUE TITLE
Adapt to `statsmodels.tsa.arima_model.ARIMA` deprecation.

### ISSUE THREAD

**Issue by csala** [MLBazaar/MLPrimitives#253]
`statsmodels` release v0.12.0 deprecated the `statsmodels.tsa.arima_model.ARIMA` model in favor of `statsmodels.tsa.arima.model.ARIMA`:

https://github.com/statsmodels/statsmodels/blob/04f00006a7aeb1c93d6894caa420698400da6c33/statsmodels/tsa/arima_model.py#L35

We should adapt to this change before they release v0.13.0, which will fully remove the `arima_model` module:

https://github.com/MLBazaar/MLPrimitives/blob/97ab03f1aa8164fb2ba58754489bfc840f47d9f9/mlprimitives/adapters/statsmodels.py#L2

**Comment by sarahmish** [comment]
Solved in #279
